/**
 * Builds src/data/themes.generated.ts from scripts/data/themes.json and the
 * vocabulary batches. Each theme lists the batch files that feed it; this
 * collects the (lemma, pos) pairs from those batches so the app can offer
 * browsable topical word sets without a content-DB schema change.
 *
 * Run: npm run build:themes  (also run by build:db)
 *
 * The generated file is committed. Fails loudly on a missing batch file, a
 * batch claimed by two themes, or a duplicate/empty theme slug.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.join(__dirname, '..');
const VOCAB_DIR = path.join(ROOT, 'scripts/data/vocab');
const THEMES_FILE = path.join(ROOT, 'scripts/data/themes.json');
const OUT_FILE = path.join(ROOT, 'src/data/themes.generated.ts');

interface ThemeSpec {
  slug: string;
  title: string;
  emoji: string;
  batches: string[];
}

interface VocabEntry {
  lemma: string;
  pos: string;
  level: string;
}

const LEVELS = new Set(['A1', 'A2', 'B1', 'B2', 'C1']);

function fail(msg: string): never {
  console.error(`build-themes: ${msg}`);
  process.exit(1);
}

function loadBatch(name: string): VocabEntry[] {
  const file = path.join(VOCAB_DIR, `${name}.json`);
  if (!fs.existsSync(file)) fail(`batch file not found: ${name}.json`);
  const entries = JSON.parse(fs.readFileSync(file, 'utf8')) as VocabEntry[];
  if (!Array.isArray(entries)) fail(`batch ${name}.json is not an array`);
  return entries;
}

function main(): void {
  const themes = JSON.parse(fs.readFileSync(THEMES_FILE, 'utf8')) as ThemeSpec[];

  const seenSlugs = new Set<string>();
  const claimedBatches = new Map<string, string>();

  const built = themes.map((theme) => {
    if (!theme.slug || !theme.title || !theme.emoji) fail(`theme missing slug/title/emoji: ${JSON.stringify(theme)}`);
    if (seenSlugs.has(theme.slug)) fail(`duplicate theme slug: ${theme.slug}`);
    seenSlugs.add(theme.slug);
    if (theme.batches.length === 0) fail(`theme has no batches: ${theme.slug}`);

    const seenWord = new Set<string>();
    const words: VocabEntry[] = [];
    for (const batch of theme.batches) {
      const owner = claimedBatches.get(batch);
      if (owner) fail(`batch ${batch} claimed by both ${owner} and ${theme.slug}`);
      claimedBatches.set(batch, theme.slug);
      for (const entry of loadBatch(batch)) {
        const key = `${entry.lemma}|${entry.pos}`;
        if (seenWord.has(key)) continue;
        if (!LEVELS.has(entry.level)) fail(`${batch}: ${key} has invalid level ${entry.level}`);
        seenWord.add(key);
        words.push({ lemma: entry.lemma, pos: entry.pos, level: entry.level });
      }
    }
    if (words.length === 0) fail(`theme ${theme.slug} resolved to no words`);
    return { slug: theme.slug, title: theme.title, emoji: theme.emoji, words };
  });

  const body =
    '// AUTO-GENERATED by scripts/build-themes.ts — do not edit by hand.\n' +
    '// Run `npm run build:themes` after changing scripts/data/themes.json or the vocab.\n\n' +
    'export interface ThemeWord {\n  lemma: string;\n  pos: string;\n  level: string;\n}\n\n' +
    'export interface Theme {\n  slug: string;\n  title: string;\n  emoji: string;\n  words: ThemeWord[];\n}\n\n' +
    `export const THEMES: Theme[] = ${JSON.stringify(built, null, 2)};\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, body);
  const total = built.reduce((n, t) => n + t.words.length, 0);
  console.log(`build-themes: wrote ${built.length} themes, ${total} words → ${path.relative(ROOT, OUT_FILE)}`);
}

main();
